### ISSUE TITLE
Adding texture?

### ISSUE THREAD

**Issue by smmsamm** [amandaghassaei/OrigamiSimulator#50] opened 2021-12-13 23:34 UTC
At first I must say I love your software,
I Thought I asked this before,
Would you please add importing an image as texture , use on obj, simulate it and export with obj as texture?

**Comment by edemaine** [comment] 2021-12-14 00:25
This is mostly a duplicate of issue #13. I'll add the obj request there.

**Closed by edemaine** 2021-12-14 00:25 UTC
